#!/usr/bin/env bash
# configure nginx to run as nginx user and listen on port 8080
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart