#!/usr/bin/env bash
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-enabled/default
service nginx restart
