#!/usr/bin/env bash
# Configures Nginx server to redirect /redirect_me with a 301 Moved Permanently

# Install nginx if not installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Create the redirection rule in the default nginx config
sudo sed -i '/location \/ {/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo systemctl restart nginx
