#!/usr/bin/env bash
# This script installs Apache2 and configures it to return Hello Holberton
apt-get update -y
apt-get install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
