#!/usr/bin/env bash
# Configure Apache server and ensure it is running
apt-get update -y
apt-get install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
service apache2 status
