#!/usr/bin/env bash
# This script configures a new Ubuntu machine to add an X-Served-By custom header
apt-get update
apt-get install -y nginx
# shellcheck disable=SC2154
printf "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
