#!/usr/bin/env bash
# Configure Nginx to listen on port 80 and restart the service

# Replace listen 8080 with listen 80 in the default site configuration
sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
