#!/usr/bin/env bash
# Ensure Nginx listens on port 80, has a valid index page, and restart the service
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
echo "Hello World from Nginx!" > /var/www/html/index.html
service nginx restart
