#!/usr/bin/env bash
# Transfers a file to a remote server
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# The script uses the 4th argument as the path to the key.
# It does NOT use a hardcoded path.
scp -o BatchMode=yes -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
