#!/usr/bin/env bash
# Transfers a file from the client to a remote server
# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Store arguments
FILE_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Perform the transfer
# -o StrictHostKeyChecking=no handles new server fingerprints
# -o BatchMode=yes prevents the command from hanging on prompts
scp -o BatchMode=yes -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$IP":~/
