#!/usr/bin/env bash
# Installs and configures Nginx web server on Ubuntu

apt-get update -y
apt-get install nginx -y

# Write the required string to Nginx default web pages
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx using init service (as systemctl is prohibited)
service nginx restart
