#!/usr/bin/env bash
# Installs and configures an Nginx web server with Holberton School text at root

apt-get update -y
apt-get install -y nginx

# Ensure the root index page contains the required string "Holberton School"
echo "Holberton School" > /var/www/html/index.html

service nginx restart
