#!/usr/bin/env bash
# Configures Nginx with a 301 redirection from /redirect_me to a target URL

apt-get update -y
apt-get install nginx -y

# Insert redirection rule inside the server block of default site configuration
sed -i "/listen 80 default_server;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }" /etc/nginx/sites-available/default

/etc/init.d/nginx restart
