#!/usr/bin/env bash
# Configures an Nginx server with a custom 404 error page containing "Ceci n'est pas une page"

apt-get update -y
apt-get install -y nginx

# Ensure the custom 404 page contains: Ceci n'est pas une page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

service nginx restart
